# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('painlevel', models.IntegerField()),
                ('headaches', models.BooleanField()),
                ('fainting', models.BooleanField()),
                ('speechloss', models.BooleanField()),
                ('occurence', models.DateTimeField()),
                ('userid', models.IntegerField()),
            ],
        ),
    ]
