# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
