# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('injury', models.CharField(max_length=200)),
                ('incidents', models.IntegerField()),
                ('incidentdate', models.DateTimeField()),
                ('recoverydate', models.DateTimeField()),
            ],
        ),
    ]
