# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
